/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainAdmin;

import entity.DataSQL;
import javax.swing.ImageIcon;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;

/**
 *
 * @author Yahiko
 */
public class MainFrame extends javax.swing.JFrame {
    private QL_Diem ql_diem;
    private QL_SinhVien ql_sinhvien;
    private ThongKe thong_ke;
    private TraCuu_Diem tracuu;
    private TrangChu trangchu;
    int index=0;
    DataSQL datasql=new DataSQL();
            
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setLocationRelativeTo(this);
//        trangchu=new TrangChu();
//        ImageIcon icon =new ImageIcon(getClass().getResource("/Image/icon/User12.png"));
//        tbl_mainboard.addTab("Trang Chủ",icon,trangchu,"Trang Chủ");
//        tbl_mainboard.setSelectedComponent(trangchu);
    }
    public MainFrame(DataSQL data) {
        initComponents();
        setLocationRelativeTo(this);
        datasql.setUsername(data.getUsername());
        datasql.setPassword(data.getPassword());
        datasql.setPort(data.getPort());
        trangchu=new TrangChu();
        ImageIcon icon =new ImageIcon(getClass().getResource("/Image/icon/home32.png"));
        tbl_mainboard.addTab("Trang Chủ",icon,trangchu,"Trang Chủ");
        tbl_mainboard.setSelectedComponent(trangchu);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btn_home = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btn_QLSV = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        btn_QLDiem = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btn_TraCuu = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        btn_ThongKe = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        tbl_mainboard = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setBackground(new java.awt.Color(204, 204, 255));
        jToolBar1.setRollover(true);
        jToolBar1.add(jSeparator2);

        btn_home.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/Home.png"))); // NOI18N
        btn_home.setText("Trang Chủ");
        btn_home.setFocusable(false);
        btn_home.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_home.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_home);
        jToolBar1.add(jSeparator3);

        btn_QLSV.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_QLSV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/User.png"))); // NOI18N
        btn_QLSV.setText("Quản Lý Sinh Viên");
        btn_QLSV.setFocusable(false);
        btn_QLSV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_QLSV.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_QLSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QLSVActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_QLSV);
        jToolBar1.add(jSeparator5);

        btn_QLDiem.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_QLDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/Temporary.png"))); // NOI18N
        btn_QLDiem.setText("Quản Lý Điểm");
        btn_QLDiem.setFocusable(false);
        btn_QLDiem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_QLDiem.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_QLDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QLDiemActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_QLDiem);
        jToolBar1.add(jSeparator4);

        btn_TraCuu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_TraCuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/statistic_48.png"))); // NOI18N
        btn_TraCuu.setText("Tra Cứu Điểm");
        btn_TraCuu.setFocusable(false);
        btn_TraCuu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_TraCuu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_TraCuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TraCuuActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_TraCuu);
        jToolBar1.add(jSeparator6);

        btn_ThongKe.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_ThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/Stats.png"))); // NOI18N
        btn_ThongKe.setText("Thống Kê");
        btn_ThongKe.setFocusable(false);
        btn_ThongKe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_ThongKe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_ThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThongKeActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_ThongKe);
        jToolBar1.add(jSeparator8);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jToolBar1, GroupLayout.DEFAULT_SIZE, 1358, Short.MAX_VALUE)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(10)
        			.addComponent(tbl_mainboard, GroupLayout.PREFERRED_SIZE, 1247, GroupLayout.PREFERRED_SIZE)
        			.addGap(26))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(jToolBar1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(tbl_mainboard, GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
        			.addContainerGap())
        );
        btn_logout = new javax.swing.JButton();
        
                btn_logout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/Bookmark.png"))); // NOI18N
                btn_logout.setText("Đăng xuất");
                btn_logout.setFocusable(false);
                btn_logout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                btn_logout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
                btn_logout.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btn_logoutActionPerformed(evt);
                    }
                });
                jToolBar1.add(btn_logout);
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_QLDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QLDiemActionPerformed
        ql_diem=new QL_Diem(datasql);
        ImageIcon icon =new ImageIcon(getClass().getResource("/Image/icon/qldiem.png"));
        tbl_mainboard.addTab("Quản Lý Điểm ",icon,ql_diem,"Quản Lý Điểm");
        tbl_mainboard.remove(index);
        tbl_mainboard.setComponentAt(index , ql_diem);
        tbl_mainboard.setSelectedComponent(ql_diem);
    }//GEN-LAST:event_btn_QLDiemActionPerformed

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
         MainFrame main=new MainFrame(datasql);
         this.dispose();
         main.setVisible(true);
    }//GEN-LAST:event_btn_homeActionPerformed

    private void btn_QLSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QLSVActionPerformed
        ql_sinhvien=new QL_SinhVien(datasql);
        ImageIcon icon =new ImageIcon(getClass().getResource("/Image/icon/User12.png"));
        tbl_mainboard.addTab("Quản Lý Sinh Viên",icon,ql_sinhvien,"Quản Lý Sinh Viên");
        tbl_mainboard.remove(index);
        tbl_mainboard.setComponentAt(index ,ql_sinhvien);
        tbl_mainboard.setSelectedComponent(ql_sinhvien);
    }//GEN-LAST:event_btn_QLSVActionPerformed

    private void btn_TraCuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TraCuuActionPerformed
        tracuu=new TraCuu_Diem(datasql);
        ImageIcon icon =new ImageIcon(getClass().getResource("/Image/icon/ticker32.png"));
        tbl_mainboard.addTab("Tra Cứu �?iểm",icon,tracuu,"Tra Cứu Điểm");
        tbl_mainboard.remove(index);
        tbl_mainboard.setComponentAt(index ,tracuu);
        tbl_mainboard.setSelectedComponent(tracuu);
    }//GEN-LAST:event_btn_TraCuuActionPerformed

    private void btn_ThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThongKeActionPerformed
        thong_ke=new ThongKe(datasql);
        ImageIcon icon =new ImageIcon(getClass().getResource("/Image/icon/Stats32.png"));
        tbl_mainboard.addTab("Thống Kê",icon,thong_ke,"Thống Kê");
        tbl_mainboard.remove(index);
        tbl_mainboard.setComponentAt(index ,thong_ke);
        tbl_mainboard.setSelectedComponent(thong_ke);
    }//GEN-LAST:event_btn_ThongKeActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
         Login_SQL login=new Login_SQL();
        this.dispose();
        login.setVisible(true);
    }//GEN-LAST:event_btn_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_QLDiem;
    private javax.swing.JButton btn_QLSV;
    private javax.swing.JButton btn_ThongKe;
    private javax.swing.JButton btn_TraCuu;
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_logout;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTabbedPane tbl_mainboard;
    // End of variables declaration//GEN-END:variables
}
