/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainAdmin;

import  entity.DataSQL;
import  entity.DiemThi;
import  entity.MonHoc;
import  entity.SinhVien;

import  Check.MessageHelper;
import  dao.DiemThiDao;
import  dao.MaHoaDes;
import  dao.MonHocDao;
import  dao.SinhvienDao;

import java.awt.BorderLayout;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.List;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;


import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author Yahiko
 */
public class TraCuu_Diem extends javax.swing.JPanel {

    /**
     * Creates new form TraCuu_Diem
     */
    String user, pass, port;
    private MainFrame parentform;
    private DefaultTableModel tblTableModell;
    DataSQL datasql = new DataSQL();

    public TraCuu_Diem() {
        initComponents();
    }

    public TraCuu_Diem(DataSQL dt) {
        initComponents();
        datasql.setUsername(dt.getUsername());
        datasql.setPassword(dt.getPassword());
        datasql.setPort(dt.getPort());
        initTable();
    }
     public void initTable(){
        tblTableModell = new DefaultTableModel();
        JScrollPane pane=new JScrollPane();
        tableScore.add(pane,BorderLayout.CENTER);
        tblTableModell.setColumnIdentifiers(new String[]{"Môn học", "Điểm giữa kỳ", "Điểm cuối kỳ" , "Điểm tổng kết"});
        tableScore.setModel(tblTableModell);
        tableScore.getTableHeader().setFont(new java.awt.Font("Times New Roman", 3, 14));
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(SwingConstants.LEFT);
        tableScore.setDefaultRenderer(Object.class,rightRenderer);
    }
    private void LoadDataTable(List<DiemThi> score ){
        try {
           for(DiemThi diem : score){

                    MonHocDao mhd=new MonHocDao();
                    MonHoc monhoc=mhd.FindMH(diem.getMaMH(), datasql);
            
               tblTableModell.addRow(new Object[]{
                   monhoc.getTenMH(), diem.getDiemGK(), diem.getDiemCK(), diem.getDiemTK()});
                 
                }
        } catch (Exception e) {
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtParam = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableScore = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_searchTen = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Account/id-card.png"))); // NOI18N
        jLabel1.setText("Mã Sinh Viên , Email , SĐT :");

        btnSearch.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Account/search.png"))); // NOI18N
        btnSearch.setText("Tra cứu");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Account/edit-user.png"))); // NOI18N
        jLabel3.setText("Họ tên");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Account/gmail.png"))); // NOI18N
        jLabel4.setText("Email");

        tableScore.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Môn học", "Giữa kỳ", "Cuối kỳ", "Tổng kết"
            }
        ));
        jScrollPane1.setViewportView(tableScore);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Account/phone.png"))); // NOI18N
        jLabel5.setText("Số điện thoại");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Account/id-card.png"))); // NOI18N
        jLabel6.setText("Mã Sinh viên");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Account/edit-user.png"))); // NOI18N
        jLabel2.setText("Họ và tên sinh viên :");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(jSeparator2, GroupLayout.PREFERRED_SIZE, 975, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED))
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel1)
        						.addComponent(jLabel2))
        					.addGap(43)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        						.addComponent(txtParam)
        						.addComponent(txt_searchTen, GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
        					.addGap(99)
        					.addComponent(btnSearch)
        					.addGap(67)))
        			.addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
        			.addGap(305))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(95)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel6)
        				.addComponent(jLabel5)
        				.addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 71, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel3))
        			.addPreferredGap(ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(txtId, GroupLayout.PREFERRED_SIZE, 227, GroupLayout.PREFERRED_SIZE)
        				.addComponent(txtName, GroupLayout.PREFERRED_SIZE, 227, GroupLayout.PREFERRED_SIZE)
        				.addComponent(txtEmail, GroupLayout.PREFERRED_SIZE, 227, GroupLayout.PREFERRED_SIZE)
        				.addComponent(txtPhone, GroupLayout.PREFERRED_SIZE, 227, GroupLayout.PREFERRED_SIZE))
        			.addGap(28)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 594, GroupLayout.PREFERRED_SIZE)
        			.addGap(241))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(22)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel1)
        						.addComponent(txtParam, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE))
        					.addGap(18)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(txt_searchTen, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(btnSearch)))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(2)
        					.addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, 149, GroupLayout.PREFERRED_SIZE)))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jSeparator2, GroupLayout.PREFERRED_SIZE, 11, GroupLayout.PREFERRED_SIZE)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(6)
        					.addComponent(jLabel6))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(18)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jScrollPane1, 0, 0, Short.MAX_VALUE)
        						.addComponent(txtId, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE))))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(txtName, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel3))
        			.addGap(35)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel4)
        				.addComponent(txtEmail, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE))
        			.addGap(29)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel5)
        				.addComponent(txtPhone, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        this.setLayout(layout);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        initTable();
        String id1 = txtParam.getText();
        String Hoten=txt_searchTen.getText();
        String id="";
        if (id1.equals("") && (Hoten.equals("")))
        {
            MessageHelper.showMesage(parentform,"Vui lòng điền thông tin tra cứu","Thông Báo");
            return;
        }
        try {
            Socket client = new Socket("localhost", 9999);
            DataOutputStream DOS = new DataOutputStream(client.getOutputStream());
            ObjectOutputStream OOS = new ObjectOutputStream(client.getOutputStream());
            ObjectInputStream OIS = new ObjectInputStream(client.getInputStream());
            if (!id1.equals("")) 
            {
                id=MaHoaDes.Encrypt(id1, id1);
            }
            else id=Hoten;  
            DOS.writeInt(6);
            System.out.println(datasql.getPort());
            OOS.writeObject(datasql);
            DOS.writeUTF(id);
            Thread.sleep(100);
            boolean check = (boolean) OIS.readBoolean();
            if (check != false) {
                SinhVien sv = (SinhVien) OIS.readObject();
                Thread.sleep(100);
                List<DiemThi> score = (List<DiemThi>) OIS.readObject();
                txtName.setText(sv.getHoTen());
                txtEmail.setText(MaHoaDes.Decrypt(sv.getEmail(), id));
                txtId.setText(MaHoaDes.Decrypt(sv.getMaSV(),id));
                txtPhone.setText(MaHoaDes.Decrypt(sv.getSDT(),id));
                LoadDataTable(score);
            } else {
                SinhVien sv = (SinhVien) OIS.readObject();
                MessageHelper.showMesage(this,"Thông tin không tồn tại \n" + "Vui lòng thử lại", "Thông Báo");
                    
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tableScore;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtParam;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txt_searchTen;
    // End of variables declaration//GEN-END:variables
}
